services:
  db:
    image: postgres:17
    container_name: data_processing_db
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080
