FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app files
COPY . .

# Expose the worker to Celery
CMD ["celery", "-A", "app.config.celery.app", "worker", "--loglevel=info"]
